### ISSUE TITLE
'paginators' is not a valid tag library: Template library paginators not found

### ISSUE THREAD

**Issue by renpj** [pydanny/dj-paginator#3]
I got this problem when loading paginator in .html

'paginator' is not a valid tag library: Template library paginator not found, tried django.templatetags.paginator,django_admin_bootstrapped.templatetags.paginator,django.contrib.admin.templatetags.paginator,django.contrib.staticfiles.templatetags.paginator,bootstrap3.templatetags.paginator,paginator.templatetags.paginator

Django version: 1.8.3, python 2.7

**Comment by pydanny** [comment]
Hi @renpj - The problem you encountered was that you were using `{% load paginator %}` instead of `{% load paginator_tags %}`. This was a documentation mistake on my part. To wit:

Use `{% load paginator_tags %}` and everything should just work.
